### ISSUE TITLE
Add Stokes V support

### ISSUE THREAD

**Issue by ajstewart** [askap-vast/vast-pipeline#223]
As title. The specifics to take into account are:

* Running with the negative source lists in addition to the 'normal' sources (do we request the user combine these outputs before running, it would make the task easier).

* Making sure ASKAP header metadata allows us to detect Stokes V (selavy had an error where it wouldn't run with the default Stokes V header, had to mimic Stokes I).

* DB unique naming needs to take into account Stokes I, V as component names from Selavy will be the same across Stokes.

**Comment by ddobie** [comment]
Closing as outdated. This can now be accomplished either with the dedicated tool @joshoewahp has written, or with vast-tools as outlined [here](https://vast-survey.org/vast-tools/notebook-examples/workshop-notebook-2023/#searching-for-stokes-v-emission)
