### ISSUE TITLE
Wrong local_rms estimation for forced fitted measurements

### ISSUE THREAD

**Issue by Andywang201605** [askap-vast/vast-pipeline#400]
When we checked the candidates from the pipeline, we found some sources with exceptional measurement errors.  
rms from the pipeline - For a selavy detection, we used image_rms value from the selavy output as the measurement errors; for a forced-fitting, we used the flux error returned by the function. 
I assume that the value in the rmsmap (noise map) at that point is the correct rms estimation. I plot the figure to check how many sources are affected. The y axis shows the ratio of local rms (rms from pipeline) to the value in the noise map. For all selavy detections, as is expected, all ratios are around 1.0. 
However, for some forced measurements, the ratios are around 2.0.
![image](https://user-images.githubusercontent.com/49584012/96879278-95405200-14c7-11eb-8a95-23f8876d3166.png)

Then I downloaded `forced_phot.py` from vast-pipeline repo and run forced-fitting for all measurements using the following parameters.
```
flux, flux_err, chisq, DOF = FP.measure(
        SkyCoord(row['ra'], row['dec'], unit=u.deg),
        cluster_threshold=3.0,
        allow_nan=False,
        edge_buffer=1.2)
```
I compared flux_err with rms value from noise map, the ratios are around 2.0. 
![image](https://user-images.githubusercontent.com/49584012/96879769-2adbe180-14c8-11eb-8615-56390aae8f9c.png)

I also used the same code to test the tile images, and the ratios are around 2.0 too.
![image](https://user-images.githubusercontent.com/49584012/96879811-34fde000-14c8-11eb-9fcd-c67aa1cadcd9.png)

As Adam suggested, I tried set `cluster_threshold=0`, but the ratios are still around 2.0
![image](https://user-images.githubusercontent.com/49584012/96879826-3a5b2a80-14c8-11eb-8bd5-931ca8c6aff3.png)

**Comment by taramurphy** [comment]
James Leung has come across this issue is trying to estimate the goodness of fit for his GRB lightcurves. Reading the log it looks like it has been solved, but possibly not deployed? Is it possible to incorporate this update? I'm not sure what the workflow is.

**Comment by dlakaplan** [comment]
@marxide could probably deploy this.

**Comment by marxide** [comment]
Sorry, I missed that ping.

Which run did you notice this error in @jameskleung?

**Comment by jameskleung** [comment]
@marxide this must have been in the original combined run (epoch 0 to 12) late last year or early this year - I think in the new runs in the dev environment, this issue has since been fixed, but will let you know if I find out otherwise.
