### ISSUE TITLE
Cloudstor source for regression tests dataset returning 403

### ISSUE THREAD

**Issue by ajstewart** [askap-vast/vast-pipeline#688]
Need to either fix or find alternative place to host the data.

The download link is: https://cloudstor.aarnet.edu.au/plus/s/xjh0aRr1EGY6Bt3/download

Says forbidden rather than folder doesn't exist.

I'm pretty sure I created the test dataset so I might be able to dig it up if required.
```
WARNING: regression test data is ~600MB ...

--2023-05-15 20:13:59--  https://cloudstor.aarnet.edu.au/plus/s/xjh0aRr1EGY6Bt3/download
Resolving cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)... 202.158.207.20
Connecting to cloudstor.aarnet.edu.au (cloudstor.aarnet.edu.au)|202.158.207.20|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
Syntax error in Set-Cookie: 5230042dc1897=6g2hqki4ckbk6b700odurovra8; path=/plus; domain=.aarnet.edu.au;; Secure; SameSite=Lax at position 76.
Syntax error in Set-Cookie: oc_sessionPassphrase=%2BA3m5emqaaSl5c%2FDV4quNWcIMAvePuLKVM8c%2BNxwcjXEc8xjYSj0qFHqAuESrIRaRX8xilc7kTrQcj36JRz08de%2FrDSGZ38kKOQJdJUGW7ZdvCaeaStkunHap%2B7KPERN; expires=Tue, 16-May-2023 20:14:01 GMT; Max-Age=86400; path=/plus;; Secure; SameSite=Lax at position 226.
2023-05-15 20:14:02 ERROR 403: Forbidden.
```

**Comment by ajstewart** [comment]
Follow up: having just looked I can confirm I have a copy of what looks like the test data.

**Comment by ddobie** [comment]
Data is here: https://www.dropbox.com/s/qbzk25rrn02qopw/pipeline-test-data.zip?dl=0

**Comment by ajstewart** [comment]
@ddobie I was going to ask if this link be dropped in, but it might be best to avoid Dropbox as they put limits on the downloads I think. Can a cloudstor or Nimbus solution be done, to replace the previous download location?

**Comment by ddobie** [comment]
Test data is now here: https://unisyd-my.sharepoint.com/:f:/g/personal/tara_murphy_sydney_edu_au/EiU1aPI4GvZCjMAFx8pjXm0BovEFB1aYDKW2YGXTl8nDqA?e=DVPWXQ

Can't seem to get an actual download link. I suspect it might be a settings/permissions issue on Tara's end, so I've asked her to investigate.
