### ISSUE TITLE
Query based on complex sky map

### ISSUE THREAD

**Issue by dlakaplan** [askap-vast/vast-pipeline#97]
Especially GW maps, but also GRB/neutrino regions.  Need to be able to link to gracedb for LIGO and/or specify via FITS.  Especially since gracedb has multiple versions.

These maps can be complex, so maybe add a column which is enclosed probability region and add ability to query based on that.

**Comment by ddobie** [comment]
@marxide did you have any plans to implement this in the pipeline software in the near future?

In principle it's wouldn't be too difficult to implement it in `vast-tools` instead - possibly actually easier. I've got most of the code already written in snippets for other purposes, so the only difficulty should (fingers crossed) be ensuring that it can handle 100k+ sources.

**Comment by marxide** [comment]
No immediate plans to tackle this on my end, but if you're able to get what you have into `vast-tools`, it should be straight forward to get it into the pipeline UI too. I expect we'd just need to take the `vast-tools` implementation and write up the part to allow users to upload the GW sky map. I'm happy to work on putting it into the pipeline after we have something in `vast-tools` that I can rip out.
